
package org.uv.tpcsw.practica03;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;

/**
 *
 * @author samantha
 */
public class EmpleadoGUI extends javax.swing.JInternalFrame {


    public EmpleadoGUI() {
        initComponents();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabBuscarID = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        Departamento = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jNombreEmpEl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnEliminarDep = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BtnBuscarTodosEmpleados = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        EmpIDBuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmpleadosporID = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EmpModTelefono = new javax.swing.JTextField();
        EmpModDireccion = new javax.swing.JTextField();
        EmpModNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnGuardarModEmp = new javax.swing.JButton();
        Departamento1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Clave = new javax.swing.JLabel();
        EmpMod = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabBuscarID.setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Guardar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 97, 168, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        jLabel4.setText("Nombre");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 41, -1, -1));

        jLabel5.setText("Direccion");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 69, -1, -1));

        jLabel6.setText("Telefono");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 168, -1));
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 66, 168, -1));

        Departamento.setText("Departamento");
        jPanel2.add(Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 140, -1, -1));

        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        List<Departamento> listaDepartamentos = session.createQuery("from Departamento", Departamento.class).list();

        // Loop through the list and add the department names to the JComboBox
        for (Departamento departamento : listaDepartamentos) {
            jComboBox1.addItem(departamento.getNombre());
        }
        session.getTransaction().commit();
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 137, 165, -1));

        TabBuscarID.addTab("Guardar", jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNombreEmpEl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNombreEmpElActionPerformed(evt);
            }
        });
        jPanel4.add(jNombreEmpEl, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 61, 163, -1));

        jLabel3.setText("Clave");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 61, -1, -1));

        jLabel7.setText("Eliminar");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 21, -1, -1));

        btnEliminarDep.setText("Eliminar");
        btnEliminarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDepActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminarDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 61, -1, -1));

        TabBuscarID.addTab("Eliminar", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnBuscarTodosEmpleados.setText("Buscar Todos");
        BtnBuscarTodosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarTodosEmpleadosActionPerformed(evt);
            }
        });
        jPanel5.add(BtnBuscarTodosEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setMaximumSize(new java.awt.Dimension(400, 100));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 500, 370));

        TabBuscarID.addTab("Buscar Todos", jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel6.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 25, -1, -1));
        jPanel6.add(EmpIDBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 25, 170, -1));

        jLabel11.setText("ID");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 28, -1, -1));

        EmpleadosporID.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        EmpleadosporID.setMaximumSize(new java.awt.Dimension(400, 100));
        jScrollPane1.setViewportView(EmpleadosporID);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 74, 424, 231));

        TabBuscarID.addTab("Buscar por ID", jPanel6);

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Modificar");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 19, 116, -1));
        jPanel3.add(EmpModTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 166, 142, -1));
        jPanel3.add(EmpModDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 138, 142, -1));

        EmpModNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpModNombreActionPerformed(evt);
            }
        });
        jPanel3.add(EmpModNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 110, 142, -1));

        jLabel8.setText("Nombre");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 116, -1, -1));

        jLabel9.setText("Direccion");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 138, -1, -1));

        jLabel10.setText("Telefono");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 166, -1, -1));

        btnGuardarModEmp.setText("Guardar");
        btnGuardarModEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModEmpActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarModEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 138, -1, -1));

        Departamento1.setText("Departamento");
        jPanel3.add(Departamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 206, -1, -1));

        Session sess = HibernateUtil.getSessionFactory().getCurrentSession();
        sess.beginTransaction();
        List<Departamento> listaDepts = sess.createQuery("from Departamento", Departamento.class).list();

        // Create a new model for jComboBox2
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();

        // Loop through the list and add the department names to the model
        for (Departamento departamento : listaDepts) {
            comboBoxModel.addElement(departamento.getNombre());
        }
        jComboBox2.setModel(comboBoxModel);
        sess.getTransaction().commit();
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 203, 165, -1));

        Clave.setText("Id de empleado a modificar:");
        jPanel3.add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 51, -1, -1));

        EmpMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpModActionPerformed(evt);
            }
        });
        jPanel3.add(EmpMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 48, 125, -1));

        TabBuscarID.addTab("Modificar", jPanel3);

        getContentPane().add(TabBuscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 6, 780, 449));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.getCurrentSession();
        Transaction t = session.beginTransaction();

        Departamento selectedDepartamento = (Departamento) jComboBox1.getSelectedItem();

        
        
        
        Empleado empleado = new Empleado();
        empleado.setNombre(txtNombre.getText());
        empleado.setDireccion(txtDireccion.getText());
        empleado.setTelefono(txtTelefono.getText());
        empleado.setDepto(selectedDepartamento);

        session.save(empleado);

        JOptionPane.showMessageDialog(this, "se guardo");

        t.commit();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnBuscarTodosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarTodosEmpleadosActionPerformed
        // TODO add your handling code here:
        
        
           // Crear el modelo de la tabla con las columnas adecuadas
        String[] columnNames = {"Clave", "Nombre", "Dirección", "Teléfono", "Departamento"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        
         
        // Obtener los datos de la base de datos usando Hibernate
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        List<Empleado> listaEmpleados = session.createQuery("from Empleado", Empleado.class).list();
        
        // Llenar el modelo de la tabla con los datos obtenidos
        for (Empleado emp : listaEmpleados) {
            String nombreDepartamento = emp.getDepto() != null ? emp.getDepto().getNombre() : "Sin departamento";
            Object[] rowData = {
                emp.getClave(),
                emp.getNombre(),
                emp.getDireccion(),
                emp.getTelefono(), 
                nombreDepartamento
            };
            model.addRow(rowData);
            System.out.println("Clave: " + emp.getClave() + ", Nombre: " + emp.getNombre() + ", Direccion: " + emp.getDireccion() + ", Teléfono: " + emp.getTelefono());
        }
        
        session.getTransaction().commit();
        
        // Añadir la tabla dentro de un JScrollPane para hacerla desplazable
       jTable2.setModel(model);
    
       
    }//GEN-LAST:event_BtnBuscarTodosEmpleadosActionPerformed

    private void jNombreEmpElActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNombreEmpElActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNombreEmpElActionPerformed

    private void btnEliminarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDepActionPerformed
        // TODO add your handling code here:

        Empleado empleado = new Empleado();
        int clave = Integer.valueOf(jNombreEmpEl.getText());
        empleado.setClave(clave);

        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.getCurrentSession();
        Transaction t=session.beginTransaction();

        Empleado empleadoEncontrado = session.get(Empleado.class,  empleado.getClave());

        if (empleadoEncontrado != null) {
            session.delete(empleadoEncontrado);
            JOptionPane.showMessageDialog(this,  "Empleado eliminado: " + empleadoEncontrado.getNombre());

        }
t.commit();
    }//GEN-LAST:event_btnEliminarDepActionPerformed

    private void EmpModNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpModNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpModNombreActionPerformed

    private void btnGuardarModEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModEmpActionPerformed
        // TODO add your handling code here:
 
        Empleado empleado = new Empleado();
        empleado.setClave(Integer.valueOf(EmpMod.getText()));

        SessionFactory sf = HibernateUtil.getSessionFactory();
        Session session = sf.getCurrentSession();
        Transaction t = session.beginTransaction();

        String selectedName = (String) jComboBox2.getSelectedItem();
        
        Map<String, Departamento> departmentMap = new HashMap<>();
        
        List<Departamento> listaDepartamentos = session.createQuery("from Departamento", Departamento.class).list();

        for (Departamento departamento : listaDepartamentos) {
            jComboBox2.addItem(departamento.getNombre());  // Add department name to JComboBox
            departmentMap.put(departamento.getNombre(), departamento);  // Map name to object]
        }

        
        if (selectedName != null) {
            Departamento selectedDepartamento = departmentMap.get(selectedName);  // Get the object from the map
            System.out.println("Selected Departamento: " + selectedDepartamento.getNombre());
        }

        Empleado empleadoEncontrado = session.get(Empleado.class, empleado.getClave());
        if (empleadoEncontrado != null) {
            empleadoEncontrado.setNombre(EmpModNombre.getText());
            empleadoEncontrado.setDireccion(EmpModDireccion.getText());
            empleadoEncontrado.setTelefono(EmpModTelefono.getText());
            empleadoEncontrado.setDepto(departmentMap.get(selectedName));

            session.update(empleadoEncontrado);
            System.out.println("Departamento actualizado: " + empleadoEncontrado.getNombre());
            JOptionPane.showMessageDialog(this, "Departamento " + empleado.getClave() + " actualizado a: " + empleadoEncontrado.getNombre());
            
        }
t.commit();
    }//GEN-LAST:event_btnGuardarModEmpActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        
        String[] columnNames = {"Clave", "Nombre", "Direccion", "Telefono", "Departamento"};
        int id = Integer.valueOf(EmpIDBuscar.getText());
        
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        // Obtener los datos de la base de datos usando Hibernate
        Session session = HibernateUtil.getSessionFactory().getCurrentSession();
        session.beginTransaction();
        List<Empleado> listaDepartamentos = session.createQuery("from Empleado", Empleado.class).list();

        // Llenar el modelo de la tabla con los datos obtenidos
        for (Empleado emp : listaDepartamentos) {
               if (emp.getClave() == id){
                
            Object[] rowData = {
             
                emp.getClave(),
                emp.getNombre(),
                emp.getDireccion(),
                emp.getTelefono(),
                emp.getDepto()
                    
            };
            model.addRow(rowData);
           
        }
        }

        session.getTransaction().commit();

        // Añadir la tabla dentro de un JScrollPane para hacerla desplazable
        EmpleadosporID.setModel(model);
        
        
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void EmpModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpModActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarTodosEmpleados;
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Clave;
    private javax.swing.JLabel Departamento;
    private javax.swing.JLabel Departamento1;
    private javax.swing.JTextField EmpIDBuscar;
    private javax.swing.JTextField EmpMod;
    private javax.swing.JTextField EmpModDireccion;
    private javax.swing.JTextField EmpModNombre;
    private javax.swing.JTextField EmpModTelefono;
    private javax.swing.JTable EmpleadosporID;
    private javax.swing.JTabbedPane TabBuscarID;
    private javax.swing.JButton btnEliminarDep;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarModEmp;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNombreEmpEl;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
